version: 2
jobs:
  build:
    environment:
      - BUNDLE_JOBS: 4
      - BUNDLE_RETRY: 3
      - BUNDLE_PATH: vendor/bundle
      - LC_ALL: en_US.UTF-8
      - LANG: en_US.UTF-8
    working_directory: /Users/distiller/project/Example
    macos:
      xcode: "9.3.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Set Git Credentials
          command: |
            git config --global --remove-section url."ssh://git@bitbucket.org"
            git config --global credential.helper store
            echo "https://larvata_taiwan:${GIT_PASS}@bitbucket.org" > ~/.git-credentials
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.4" > ~/.ruby-version
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems-
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - v1-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            if [ ! -d "Pods" ]; then
              curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
              bundle exec pod install
            fi
      - save_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            
        # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Moya-Pretty-Example

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
